### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by AndrewSB** [krrishd/gitio#2]
<img width="605" alt="screen shot 2016-12-13 at 3 42 50 pm" src="https://cloud.githubusercontent.com/assets/3814772/21163945/dda2a36a-c14a-11e6-9b7d-9944433f1720.png">

**Comment by krrishd** [comment]
Hey Andrew --

It does still work, the issue you're encountering is just something I forgot to document: if you've already made a short git.io URL from a URL, it'll just give you that old one.

To bypass that issue, try running that with something like https://www.github.com/AndrewSB?v1 instead so the git.io service treats it as an entirely new URL.

Lemme know if that doesn't fix things.

**Comment by AndrewSB** [comment]
yup, that fixed it @krrishd, thanks!
